import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import { Merienda } from "next/font/google";
import Footer from "@/components/Footer";


const merienda = Merienda({
  weight:['400'],
  subsets : ['latin'],
  variable : '--font-merienda'
})

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${merienda.variable}`}>
      <body className="text-white font-merienda" style={{backgroundColor : "#517664" }}
      >
        <Header />
        {children}
        <Footer />
        </body>
    </html>
  );
}
